### ISSUE TITLE
Feature: override static_lambda in specs

### ISSUE THREAD

**Issue by TamasSzigeti** [PedroTroller/PhpCSFixer-Custom-Fixers#126]
Thanks for this package!

Given static lambdas do not work with phpspec, how about adding this to the phpspec rules, to drop the static from lambdas in the spec files, similar to how visibility is dropped?

TIA

**Comment by PedroTroller** [comment]
@TamasSzigeti can you give me an example ?

**Comment by TamasSzigeti** [comment]
Sorry for the lack of details. What I meant is that when you pass a callback to `will()` and cs-fixer adds `static` to it, then it failed with
```
warning: Cannot bind an instance to a static closure in vendor/phpspec/prophecy/src/Prophecy/Promise/CallbackPromise.php line 61
```

Interestingly, I can't reproduce it anymore, so I guess it was fixed somewhere along the way. Closing this, thank you though!

**Comment by TamasSzigeti** [comment]
Ah sorry it does reproduce, I was looking at the wrong place. So it would be nice if we could use `static_lambda` and this package would override it for spec files.

Shall I provide full example or this is clear enough?

**Comment by PedroTroller** [comment]
Looks clear. I will try to find a solution ;)

**Comment by PedroTroller** [comment]
Thanks @TamasSzigeti :wink:
