### ISSUE TITLE
useless_comment remove close comment tag

### ISSUE THREAD

**Issue by grachevko** [PedroTroller/PhpCSFixer-Custom-Fixers#27]
![image](https://user-images.githubusercontent.com/8628465/43185509-d0c2628c-8ff4-11e8-82fc-a6deb3ac42ea.png)

**Comment by PedroTroller** [comment]
![image](https://user-images.githubusercontent.com/1766827/43205805-8141ab7a-9024-11e8-86b6-0616c99441b9.png)

Let me check :wink:

**Comment by PedroTroller** [comment]
BTW, can I keep your code to add it as a non-regression test ?

**Comment by grachevko** [comment]
yes, sure
