### ISSUE TITLE
useless_comment save empty line

### ISSUE THREAD

**Issue by grachevko** [PedroTroller/PhpCSFixer-Custom-Fixers#29]
![image](https://user-images.githubusercontent.com/8628465/43254304-c3b4dde6-90cf-11e8-9260-f980d6839c9d.png)

Second run don't remove empty line. 
Empty line was removed after removed `PedroTroller/useless_comment` from rules.

**Comment by PedroTroller** [comment]
In fact I've decided to not fixe this behavior because there is an other fixer for that case : `phpdoc_trim`. I'le try to fix it later (so I will not close this PR), but for the moment you can use this other fixer.

**Comment by grachevko** [comment]
This other fixer active (i guess it included to @symfony). 
But it not work if fixers from this repo are active. Only if i deactivate it this fixer will work,
