### ISSUE TITLE
Do not take into account default values in LineBreakBetweenMethodArgumentsFixer

### ISSUE THREAD

**Issue by roukmoute** [PedroTroller/PhpCSFixer-Custom-Fixers#64]
I think it could be a plus to do not take into account default value when an array is not empty, or via a new parameter.  
I pass few minutes to search why it "line breaks" with theses only parameters :
```
'PedroTroller/line_break_between_method_arguments' => [
    'max-length' => 120,
    'automatic-argument-merge' => false,
],
```

And it is because `max-args` comes in conflict with my values, but I don't care of this parameter.

**Comment by PedroTroller** [comment]
@roukmoute can you provide some examples ?

**Comment by roukmoute** [comment]
With my configuration in the first post:

```php
public function doesNotExceed120Characters($param1, $param2, $param3, $param4, $param5) {
}
```

Is refactored to:

```php
public function doesNotExceed120Characters(
    $param1,
    $param2,
    $param3,
    $param4,
    $param5
) {
}
```

And it's due to the parameter `max-args`, but I don't care of it.

**Comment by PedroTroller** [comment]
Just set it to a billion ;)

**Comment by roukmoute** [comment]
This is what I did, but this is not a solution, thanks for your response.

**Comment by PedroTroller** [comment]
@roukmoute @flug https://github.com/PedroTroller/PhpCSFixer-Custom-Fixers/pull/65/files#diff-04c6e90faac2675aa89e2176d2eec7d8R420
Something like that ?

**Comment by PedroTroller** [comment]
![image](https://user-images.githubusercontent.com/1766827/67371077-0f1fc180-f57c-11e9-8377-3e95eb6a3d34.png)
 What a violence!

**Comment by roukmoute** [comment]
This is better!

But for me this is not related directly to `LineBreakBetweenMethodArgumentsFixer` but to all your rules.
I think you should add all options and its default in your documentation or ignore value when it is not defined in the configuration file.

**Comment by flug** [comment]
![Wathing you](https://media.giphy.com/media/xUA7b409CMyKo9PJQY/giphy.gif)

**Comment by PedroTroller** [comment]
> This is better!
> 
> But for me this is not related directly to `LineBreakBetweenMethodArgumentsFixer` but to all your rules.
> I think you should add all options and its default in your documentation (we don't know that example it is in the readme are the default rules), or ignore value when it is not defined in the configuration file.

@roukmoute you know that this is an open source project you can contribute on... 
![image](https://user-images.githubusercontent.com/1766827/67584259-80629e80-f74d-11e9-88f8-b97f1ea716be.png)

**Comment by roukmoute** [comment]
I'm too young for that
